TEColorParameter and custom ui
titanicsend/LXStudio-TE pull request #195
Opened 2023-04-18 20:59 UTC by jkbelcher

New TEColorParameter gives patterns 3 ways to consume color, wrapped in one convenient parameter:
- Solid color
- Two solid colors
- Gradient

Open Belcher_color.lxp to see example patterns of each.

It’s easiest to use with a midi controller attached… a knob mapped to this parameter turns the subparameter “Offset”.  Offset shifts the solid colors as well as the gradient.  If you don’t have a midi controller just click on the parameter and drag Offset with the mouse.

Includes a custom UI for TEPerformancePattern (knobs visually line up with the MidiFighterTwister), and a custom overlay UI for the new color parameter.

Added [the beginning of] a TE-specific Gradient pattern and a TESolidPattern as examples.  And modified @raldi 's Checkers pattern for a two-color example.

2023-04-18 21:18 UTC, jkbelcher commented
This makes it easy for patterns to stay within the palette and brings the TE gradients documented by @jvyduna to the surface for easy consumption.  And keeps things runtime adjustable by the user.

2023-04-18 23:39 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/mike/Checkers.java
> +    int color1 = getCurrentColor2();
Ha I was going for minimal lines changed but yes that's silly.

2023-04-18 23:43 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/mike/Checkers.java
> +    int color1 = getCurrentColor2();
Fixed.

2023-04-19 03:02 UTC, zranger1 requested changes
Working fine here!

2023-04-19 14:56 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/TEPerformancePattern.java
> +            .setDescription("Which TEGradient to use. Full_Pallete=entire, Foreground=Primary-Secondary, Primary=Primary-BackgroundPrimary, Secondary=Secondary-BackgroundSecondary");
Thx, fixed.

2023-04-20 02:39 UTC, zranger1 approved these changes
Approved!   Merge as soon as we get the Pixelblaze framework PR in!

2023-04-20 15:43 UTC, merged