Tools for Updating FragmentShaderEffect Patterns
titanicsend/LXStudio-TE pull request #199
Opened 2023-04-22 02:39 UTC by zranger1

A few changes needed to simplify converting these patterns to use the common controls, plus a sample conversion of the NeonSnakeShader pattern.

This is a straightforward, very vanilla conversion, showing how to set up and use the common controls in this pattern framework.  We can add more features to this pattern later if necessary.  Controls are:

- Color: Yes
- Speed: Yes
- X/Y Offset: Y only, since the pattern moves constantly in X
- Spin/Angle:  No.
- Brightness: Yes
- Size:  Snake size
- Quantity:  No
- Wow1:  Base Glow
- Wow2:  Beat reactive snake size modulation
- Wow Trigger: No

2023-04-22 13:41 UTC, jkbelcher requested changes
The controls look good on NeonSnakeShader.  Let's switch to the `getControls()` method at least for non-child classes.  Otherwise just minor cleanup comments.

2023-04-22 13:41 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/TEPerformancePattern.java
> +    public TECommonControls controls;
Let's do the LX style here of keeping this protected, (or better private but that would take a wide refactor), and use an accessor method for public access.  It keeps someone from replacing the variable which would leave us in a bad state if we had listeners attached.
```
private/protected TECommonControls controls;
public TECommonControls getControls() {
  return this.controls;
}
```

2023-04-22 13:41 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/yoffa/effect/shaders/NeonSnakeShader.java
> +        colorToRGBArray(pattern.calcColor(), waveColor);
Ideally on a pattern rendering a solid color we'd only call pattern.calcColor() once per frame, not once per pixel.  Am I reading correctly that this will get called once per pixel?

Maybe we should modify the calcColor() method to do the math only once per frame, then we don't have to worry about it out here in the patterns.  Can save that for a different PR.

2023-04-22 13:41 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/yoffa/effect/shaders/NeonSnakeShader.java
There are some unused imports on this file.

2023-04-22 13:41 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/yoffa/effect/shaders/FragmentShaderEffect.java
> +import static titanicsend.util.TEMath.multiplyVectorByMatrix;
These 3 imports are unused.

2023-04-22 13:41 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/yoffa/framework/PatternEffect.java
Two unused imports here.

2023-04-22 15:02 UTC, zranger1 commented on src/main/java/titanicsend/pattern/yoffa/effect/shaders/NeonSnakeShader.java
> +        colorToRGBArray(pattern.calcColor(), waveColor);
It does, and that is bad.

This is a deprecated legacy framework though, and I'm trying to invest the smallest possible amount of time to get the handful of patterns that use it running.   If these patterns show a big frame rate drop when tested, rather than fix the framework, I think we should encourage people to port to normal TEPerformancePattern patterns (or OpenGL).

And yes, in the case of calcColor()  and probably others, it'd be good to calculate only once per frame.  But only if it's relatively uncomplicated to do so since we have so little time for testing and bug fixes before EDC.

The Historical Record:
It's from before my time, and from very early in TE's development -- a fragment shader emulation framework in Java.  The idea was that you translate a shader into a ```getColorForPoint()``` function and you're basically done.  All the per frame (rather than per pixel) setup is done somewhere above this in the hierarchy.

So to add per-frame color and rotation and all the other modern conveniences, we'd have to dig in and touch some code that I'd prefer to leave alone until we can safely remove it.

2023-04-22 15:03 UTC, zranger1 commented on src/main/java/titanicsend/pattern/yoffa/effect/shaders/NeonSnakeShader.java
Will fix in next commit

2023-04-22 15:04 UTC, zranger1 commented on src/main/java/titanicsend/pattern/yoffa/effect/shaders/FragmentShaderEffect.java
> +import static titanicsend.util.TEMath.multiplyVectorByMatrix;
Will fix in next commit.

2023-04-22 15:04 UTC, zranger1 commented on src/main/java/titanicsend/pattern/yoffa/framework/PatternEffect.java
Will fix in next commit.

2023-04-22 15:06 UTC, zranger1 commented on src/main/java/titanicsend/pattern/TEPerformancePattern.java
> +    public TECommonControls controls;
Good idea!   Will implement in the next commit.  (Although if anybody replaces this variable, they kinda... deserve what they get.   With great power comes great responsibility!)

2023-04-22 16:49 UTC, zranger1 commented on src/main/java/titanicsend/pattern/yoffa/effect/shaders/NeonSnakeShader.java
> +        colorToRGBArray(pattern.calcColor(), waveColor);
Ok.   I fixed this for rotation and color - this style of pattern is CPU intensive enough that it's worth a little work to keep overall performance high.   Added functions:

- `calcColor()`
-` calcColor2()`
- `rotate2D(point,origin) `

to FragmentShaderEffect class, and added spin support to NeonSnakeShader.  (Angle might actually be useful with this pattern.  Not so sure about actually spinning that snake around.   But it works as an example.)

2023-04-22 23:28 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/TEPerformancePattern.java
> +                        .setDescription("For a solid color: Whether to use global TE palette (preferred), or a static color unique to this pattern");
Hey @zranger1 the refactor on this file now has lines using 6 and even 8 spaces for indentation.  4 was standard on the file.

2023-04-22 23:30 UTC, zranger1 commented on src/main/java/titanicsend/pattern/TEPerformancePattern.java
> +                        .setDescription("For a solid color: Whether to use global TE palette (preferred), or a static color unique to this pattern");
I just ran the usual automated tool on it.  Wonder what happened.

2023-04-22 23:35 UTC, zranger1 commented on src/main/java/titanicsend/pattern/TEPerformancePattern.java
> +                        .setDescription("For a solid color: Whether to use global TE palette (preferred), or a static color unique to this pattern");
Oh... it looks like ideaJ uses a different convention for continued lines.  At least it's consistent throughout.   I'll see if I can convince it to be a little more conservative about the number of spaces.

2023-04-22 23:42 UTC, zranger1 commented on src/main/java/titanicsend/pattern/TEPerformancePattern.java
> +                        .setDescription("For a solid color: Whether to use global TE palette (preferred), or a static color unique to this pattern");
Ok... should take up a little less space now.   I wonder who decides what the defaults are for this stuff...

2023-04-23 12:36 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/TEPerformancePattern.java
> +                        .setDescription("For a solid color: Whether to use global TE palette (preferred), or a static color unique to this pattern");
Formatting looks mostly fixed now.  Have a couple stray "<p>" lines, will flag.

2023-04-23 12:39 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/TEPerformancePattern.java
> +         * <p>
Formatter blip.

2023-04-23 12:39 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/TEPerformancePattern.java
> +     * <p>
Formatter blip.

2023-04-23 12:39 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/TEPerformancePattern.java
> +     * <p>
Formatter blip.

2023-04-23 12:53 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/yoffa/effect/shaders/NeonSnakeShader.java
> +        colorToRGBArray(pattern.calcColor(), waveColor);
Looks good.  I can do a quick mod to TEPerformancePattern to make this safer too.

2023-04-23 12:55 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/yoffa/framework/PatternEffect.java
Still have 2 here.

2023-04-23 13:19 UTC, jkbelcher approved these changes
I just added the last formatting changes.  I'm away from the desk today so no need to keep holding this up over minor formatting.  Carry on!

2023-04-23 13:20 UTC, merged