updating panels ip/channel config + script
titanicsend/LXStudio-TE pull request #241
Opened 2023-05-12 09:02 UTC by theyoffa

Changes:

- Add script to process backpacks tab of the spreadsheet into update ip/controller panel configs
- Check in updated config
- Update channels per IP to 4 (from 8) and pixels per channel to 250 (from 500) per our new controller design
- Add multi-ip/overflow functionality for panels which have over 1000 pixels

TODO:

- Investigate [this](https://titanicsend.slack.com/archives/C047AD94VCG/p1683244280798419?thread_ts=1683128931.145489&cid=C047AD94VCG) special case 
- Check with Keegan on missing panel (and edge) data

2023-05-12 09:05 UTC, theyoffa commented on src/main/java/titanicsend/model/TEStripingInstructions.java
> +  public static final int DEFAULT_CHANNEL_LENGTH = 250;
According to this [thread](https://titanicsend.slack.com/archives/C047AD94VCG/p1683244047978589?thread_ts=1683128931.145489&cid=C047AD94VCG) it sounds we have to address having different length for channels/edges. That said, doesn't look like we have anything longer than 250 in edges.txt and doesn't seem like we use this value for edges anyway. If that's because edges.txt is currently incomplete, we can rename to panel_length.

2023-05-12 13:09 UTC, jkbelcher requested changes
Nice, great to be getting these config updates in.  I'm getting an error though...

2023-05-12 13:09 UTC, jkbelcher commented on src/main/java/titanicsend/model/TEStripingInstructions.java
> +  public static final int DEFAULT_CHANNEL_LENGTH = 250;
Yeah in that thread Keegan says some edges are still in the 400-500 range for pixel count.  So let's split this into something like `DEFAULT_CHANNEL_LENGTH_EDGE` and `DEFAULT_CHANNEL_LENGTH_PANEL`, and we'll need handling to use the two of them.

2023-05-12 17:23 UTC, raldi commented on src/main/java/titanicsend/model/TEStripingInstructions.java
> +  public static final int DEFAULT_CHANNEL_LENGTH = 250;
Note that this constant is within TEStripingInstructions, which relates to the striping of panels. So indeed, if we wanted to be explicit, we could call this class TEPanelStripingInstructions and the constant DEFAULT_NUMBER_OF_PIXELS_TO_USE_WHEN_STRIPING_A_PANEL_BEFORE_ROLLING_OVER_TO_THE_NEXT_CHANNEL. I'll leave it up to you to decide which of those words to keep and which to omit. :D

2023-05-12 17:26 UTC, raldi commented on src/main/java/titanicsend/model/TEWholeModel.java
> +          int channelNum = Integer.parseInt(tokens[1]);
Panels always start at channel index 0, right? In other words, although we do this:

[controller] - [edge] - [edge]

...we never do this:

[controller] - [edge] - [panel]

or:

[controller] - [panel] - [panel]

...right? If so, we don't need to have ":0" in the panel config because it's always ":0" (and besides, even for edges, ":0" is implied when there's no colon.

2023-05-12 17:36 UTC, raldi requested changes
This is a great first stab at a really hairy task. You're almost there, keep at it!

2023-05-12 17:36 UTC, raldi commented on resources/vehicle/panels.txt
> +FA	89-91	89-126	91-126	91->89	unflipped	10.7.21.211#1:0/10.7.21.212#1:1000
This seems wrong; 10.7.21.212#1:1000 means, "Part of Panel FA is going to be on Channel 1 of controller 10.7.21.212, 1000 pixels into that controller's output line." That would correspond to something like:

[controller's channel 1] - [edge with 800 pixels] - [edge with 200 pixels] - [this part of Panel FA]

2023-05-12 17:36 UTC, raldi commented on script/import-tsv/import-panels.py
> +del tsv_data[0:3]
This could use a comment like:

```
# The first three lines of that tab are header notes, and we're not
# going to bother asserting that they contain any particular text
```

2023-05-12 17:36 UTC, raldi commented on script/import-tsv/import-panels.py
> +                output = row[0] + "#" + str(channel_number) + ":" + pixel_start
As noted in the Java commentary, the number after the colon isn't supposed to be the index into the fixture; it's supposed to be the index into the controller channel.

2023-05-12 17:36 UTC, raldi commented on script/import-tsv/import-panels.py
> +# Cross-reference and update
You're doing an impressive job handling the nightmare that is automated config updating from spreadsheet dumps.

2023-05-12 17:36 UTC, raldi commented on src/main/java/titanicsend/model/TEWholeModel.java
> +            throw new RuntimeException("Not enough ips! May require a missing overflow ip");
I used to throw exceptions for bad output configs, but the 2023 pattern programmers have been moving them to warnings, so they can keep writing patterns even after we check in a broken output config. After some consideration, I've come to see the wisdom of this new approach.

2023-05-12 17:36 UTC, raldi commented on src/main/java/titanicsend/model/TEWholeModel.java
> +
Add:

```
// TODO: Mike really should've added a comment here explaining what's going on. Figuring
// out which Mike is an exercise for the reader.
```

2023-05-12 17:56 UTC, jkbelcher commented on src/main/java/titanicsend/model/TEWholeModel.java
> +            throw new RuntimeException("Not enough ips! May require a missing overflow ip");
And not just for pattern development, but you can keep sending pixels to the car for hardware debugging while you're working on the config for a single item.

2023-05-12 18:48 UTC, theyoffa commented on src/main/java/titanicsend/model/TEStripingInstructions.java
> +  public static final int DEFAULT_CHANNEL_LENGTH = 250;
made the variable name panel specific and leveraged your full name as a comment :)

@justin shouldn't need to do anything for the edges

2023-05-12 18:48 UTC, theyoffa commented on src/main/java/titanicsend/model/TEWholeModel.java
> +          int channelNum = Integer.parseInt(tokens[1]);
sg, killed it

2023-05-12 18:50 UTC, theyoffa commented on src/main/java/titanicsend/model/TEWholeModel.java
> +            throw new RuntimeException("Not enough ips! May require a missing overflow ip");
ugh pattern devs amiright? :)

moved to warn

2023-05-12 18:51 UTC, theyoffa commented on src/main/java/titanicsend/model/TEWholeModel.java
> +
:) added some comment

2023-05-12 21:06 UTC, theyoffa commented
added functionality for our manufacturing defects. unfortunately smaller channel size means we need to be more specific about where they are and will require manual inspection :/. Took a 50/50 shot at guessing each time for now.

2023-05-12 21:26 UTC, raldi commented
This moves the ball substantially closer to the end zone. I recommend we merge it in and address the remaining bits in the next PR.

2023-05-12 21:26 UTC, raldi approved these changes

2023-05-12 22:14 UTC, jkbelcher commented on src/main/java/titanicsend/model/TEWholeModel.java
> +            continue;
@theyoffa This will infinite loop.

Also recommend `TE.err("...")` instead of `LX.log()`

2023-05-12 22:17 UTC, raldi commented on src/main/java/titanicsend/model/TEWholeModel.java
> +            continue;
Yeah, I think just `break` and leave the rest of the fixture dark.

2023-05-12 23:02 UTC, theyoffa commented on src/main/java/titanicsend/model/TEWholeModel.java
> +            continue;
🤦‍♂️ good catch, fixed

2023-05-13 03:34 UTC, jkbelcher approved these changes

2023-05-13 03:36 UTC, jkbelcher commented
Next time I won't do a blocking review when there are Two Mikes on the situation

2023-05-13 03:36 UTC, merged