More digitized panels
titanicsend/LXStudio-TE pull request #348
Opened 2023-07-16 03:46 UTC by kryptonat

- PCA
- PED
- PFA
- PAC
- PAB

2023-07-16 17:33 UTC, raldi approved these changes

2023-07-17 07:35 UTC, raldi requested changes

2023-07-17 07:35 UTC, raldi commented on resources/vehicle/striping-instructions.txt
> +PFC 30 L . +. . . -------------------. . +. . +. . +. . +. .
I'm gonna want to see a photo of this one.

2023-07-27 02:26 UTC, raldi commented
PFC needs work but the rest looks good

2023-07-27 02:29 UTC, kryptonat commented
PFC is not part of this PR so if this is good, can you approve and merge?

2023-07-27 14:15 UTC, raldi approved these changes

2023-07-27 14:15 UTC, merged