Adding PFC and PDB
titanicsend/LXStudio-TE pull request #356
Opened 2023-07-22 19:07 UTC by jsohi11

See Slack for next steps for PFC: https://titanicsend.slack.com/archives/C02L0MDQB2M/p1689173793633949

PDB has been completed (partially coded previousl)

2023-07-22 20:35 UTC, raldi requested changes

2023-07-22 20:35 UTC, raldi commented on resources/vehicle/striping-instructions.txt
> +PFC 30 R . +. . . -------------------. . +. . +. . +. . +. . +. g ++++++++++++++++++. . +. . . +. . . +. . . +. . . +. . . +. . . . +. . +. . . . +. .
See Slack; I'm afraid this will have to be redone after the row with all the pluses. But that should be mostly popping work, because I believe the only change you'll need to make here is to remove the "." row after the one with all the pluses.

2023-08-02 02:19 UTC, kryptonat commented on resources/vehicle/striping-instructions.txt
> +PFC 30 R . +. . . -------------------. . +. . +. . +. . +. . +. g ++++++++++++++++++. . +. . . +. . . +. . . +. . . +. . . +. . . . +. . +. . . . +. .
No longer relevant in this PR. PFC was fixed in another PR https://github.com/titanicsend/LXStudio-TE/commit/1f5f041835a89e8ff20dbf670865f6a3aff021f4

2023-08-02 02:20 UTC, kryptonat approved these changes

2023-08-02 02:21 UTC, raldi approved these changes

2023-08-02 02:59 UTC, merged