TEAutopilot MVP
titanicsend/LXStudio-TE pull request #45
Opened 2022-06-27 16:55 UTC by worldveil

Introduces `TEAutopilot` class which is an `LXLoopTask` that now runs on normal FPS schedule along with main thread. 

<img width="798" alt="Screen Shot 2022-06-30 at 10 04 31 PM" src="https://user-images.githubusercontent.com/1045250/176827294-ea0324c7-dc89-40d1-a5ea-357ea7778e56.png">

`TEAutopilot`'s job (only when `enabled=true`) is to observe OSC messages and audio state to automatically trigger channels, patterns, and clips when appropriate. 

A few notes:

- `TEBeatEvent`, `TEPhraseEvent`, `TEOscMessage` : structs to hold data about past events
- `TEChannelName`, `TEPhrase` : enums corresponding to channels in AutoVJ .lxp and phrase types, respectively
- `TETimeUtils`, `TEMixerUtils` : utiility functions to aid in calculations or manipulating LX mixer
- `TEHistorian` : wrapper around historical data that `TEAutopilot` relies on to understand the past
- `CircularArray`: constant size storage and access time buffer to handle storage of a small window of previous events

Two main settings control how autopilot works:

- `enabled` is whether or not autopilot will actually act, with this off the loop simply exits out after checking state. You may toggle this in Global UI of LX Studio
- `autoBpmSyncEnabled`: ALPHA! if this is `true`, autopilot will detect when LX's BPM drifts too far outsize what OSC messages on beats are indicating. ANY OSC message from ShowKontrol overrides this -- this is just to fine tune when sometimes setBPM messages do not come or are slightly wrong. I have found this in practice to happen occasionally.  It is my hope we can find a way to have ShowKontrol just output the correct value or some other fix and we can delete this setting!

2022-06-27 16:57 UTC, worldveil commented
WIP, don't merge

2022-07-06 21:32 UTC, raldi requested changes
Wow! Just some cleanups. Let's get all the printf's changed to proper logging.

2022-07-06 21:32 UTC, raldi commented on src/main/java/titanicsend/app/TEApp.java
> +  public static class AutopilotComponent extends LXComponent implements LXOscComponent {
This too would probably be better in its own file.

2022-07-06 21:32 UTC, raldi commented on src/main/java/titanicsend/app/TEApp.java
> +  public static class AutopilotUIComponent extends UICollapsibleSection {
This too

2022-07-06 21:32 UTC, raldi commented on src/main/java/titanicsend/app/TEAutopilot.java
> +    // our ref to global LX object
This one probably doesn't need a comment, but the one above does

2022-07-06 21:32 UTC, raldi commented on src/main/java/titanicsend/app/TEAutopilot.java
> +                System.out.printf("BPM est from beats: %f, LX BPM is: %f, overriding BPM --> %f!\n"
Why not lx.log()?

2022-07-06 21:32 UTC, raldi commented on src/main/java/titanicsend/app/TEAutopilot.java
> +                    // this should never happen, since we test for size() of queue, but good to check
Maybe log something here?

2022-07-06 21:32 UTC, raldi commented on src/main/java/titanicsend/app/TEAutopilot.java
> +                    System.out.printf("Don't recognize OSC message: %s\n", address);
LX.error()

2022-07-07 07:03 UTC, theyoffa commented on src/main/java/titanicsend/app/TEAutopilot.java
> +    public ArrayList<LXClip> collectClipsToTrigger(TEPhrase newPhrase, boolean isSamePhrase) {
not really familiar with LXClips and what we're doing here but it seems cool! would love to chat about it next meeting.

2022-07-07 07:12 UTC, theyoffa commented on src/main/java/titanicsend/app/TEAutopilot.java
> +                oldNextChannelName = TEMixerUtils.getChannelNameFromPhraseType(oldNextPhrase);
so i guess when this happens we would be teasing a transition to a new pattern, then shutting it off when the next phrase comes? maybe fine/looks on purpose :)

2022-07-07 07:13 UTC, theyoffa commented on src/main/java/titanicsend/app/TEAutopilot.java
> +                //setChannelTo(oldNextChannel, LEVEL_OFF);
i think we need this?

2022-07-07 07:13 UTC, theyoffa commented on src/main/java/titanicsend/app/TEAutopilot.java
> +    public TEPhrase guessNextPhrase(TEPhrase newPhrase) {
what will happen here if the DJ starts playing loops? will all our predictions be wrong?

2022-07-07 07:17 UTC, theyoffa commented on src/main/java/titanicsend/app/TEAutopilot.java
> +            // TODO(will) for when we want to act without OSC messages -- just based on pure audio
we're already doing some of this in TEAudioPattern. when the time comes, might sense to extract into something that works for both use cases...like a TE wrapper to the lx engine

2022-07-07 07:20 UTC, theyoffa commented on src/main/java/titanicsend/app/autopilot/TEBeatEvent.java
> +public class TEBeatEvent {
unless you're planning on adding more here, you could prolly just use the a long directly rather than wrapping it.

2022-07-07 21:34 UTC, worldveil commented on src/main/java/titanicsend/app/autopilot/TEPhrase.java
> +        ConcurrentHashMap<String, TEPhrase> m = new ConcurrentHashMap<String, TEPhrase>();
oh this is super cool!

but doesn't seem to work for ConcurrentHashMaps?

```
no instance(s) of type variable(s) K, V exist so that Map<K, V> conforms to ConcurrentHashMap<String, TEPhrase>
```

?

2022-07-07 21:36 UTC, worldveil commented on src/main/java/titanicsend/app/autopilot/TEPhrase.java
> +        //m = (ConcurrentHashMap<String, TECanonicalPhrase>) Collections.unmodifiableMap(stringToPhrase);
oh duh

2022-07-07 21:37 UTC, worldveil commented on src/main/java/titanicsend/util/CircularArray.java
> +public class CircularArray<T> {
Ah, but I wanted index access - don't think these have them right? I couldn't find anything that was both a circular array and had support to query by index

2022-07-07 21:39 UTC, worldveil commented on src/main/java/titanicsend/app/autopilot/TEChannelName.java
> +    public int getIndex() {
that constrains us to have contiguous, ordered indices though right? I wanted flexibility in case we wanted to skip a channel or something

2022-07-07 21:42 UTC, worldveil commented on src/main/java/titanicsend/app/autopilot/TEOscPath.java
> +public class TEOscPath {
ah great point

2022-07-07 22:04 UTC, worldveil commented on src/main/java/titanicsend/app/TEAutopilot.java
> +    private static double LEVEL_FULL = 1.0,
added!

2022-07-07 22:05 UTC, worldveil commented on src/main/java/titanicsend/app/TEAutopilot.java
> +            // TODO(will) for when we want to act without OSC messages -- just based on pure audio
hmm yeah could yes

2022-07-07 22:06 UTC, worldveil commented on src/main/java/titanicsend/app/TEAutopilot.java
> +                    // this should never happen, since we test for size() of queue, but good to check
added one!

2022-07-07 22:07 UTC, worldveil commented on src/main/java/titanicsend/app/TEAutopilot.java
> +        oldNextPhrase = nextPhrase;
curPhrase is always certain

nextPhrase is uncertain

2022-07-07 22:08 UTC, worldveil commented on src/main/java/titanicsend/app/TEAutopilot.java
> +        oldNextPhrase = nextPhrase;
the point of reference is always at current moment, since that's when we receive the OSC phrase message. that's the reason for the awkward wording

2022-07-07 22:21 UTC, merged