Adding the TE-Projection Touchdesigner App
titanicsend/LXStudio-TE pull request #496
Opened 2024-06-26 01:09 UTC by sina-cb

This PR adds some new changes to the ModelFileWriter to write out the mask PNG files along with UV coordinates.

This PR also adds some refactoring to the ModelFileWriter to make it easier to support boot up model updates.

2024-07-09 22:29 UTC, zranger1 requested changes
This works very well!  Just for the sake of neatness, remove the unused imports, and I'll approve. 

And thanks for talking to projection people and figuring out what they needed!  In my corner of the universe, uv coordinates are always 0.0 to 1.0 floating point.   Never would've occurred to me that they'd want something different.

2024-07-13 13:53 UTC, jkbelcher reviewed
Given the size of these binaries I'm wondering if we should start a new repo for the TD app.

Also - the png files will change every time a panel is adjusted, right?  Which will happen every show.  Maybe we should exclude them from the repo and generate as-needed, given they're large files and almost guaranteed to be out of date.

2024-07-13 13:53 UTC, jkbelcher commented on Projects/CoachellaMaster.lxp
Let's not overwrite the CoachellaMaster project file.  It should be preserved for reference.  If you think the NDI stuff needs an example file just make a new one.  OTOH if a project file was just for testing let's avoid commiting them because it bloats the repo.  Those changes get pulled forever when someone runs `git clone`.

2024-07-13 13:53 UTC, jkbelcher commented on .gitignore
> +TD/TE-Projection/Backup/
Should this be a local gitignore or does the TD app generate this folder?

2024-07-13 13:53 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/jon/ModelFileWriter.java
> +    if (doneWriting) {
Thanks for moving this out of the `for` loop.

2024-07-13 13:53 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/jon/ModelFileWriter.java
> +      doneWriting = true;
Maybe move this to the start of the `try` block?  If the file operation fails it's going to try again every frame which could be a problem.

2024-07-13 13:53 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/sinas/TdNdiPattern.java
> +  protected NDIEngine ndiEngine;
Why did all this stuff get moved?  Was the formatter not run before?

2024-07-13 14:06 UTC, jkbelcher commented
Would like to get @zranger1 's eyes on the changes to ModelFileWriter and TdNdiPattern.

2024-07-13 19:58 UTC, zranger1 commented
Both ModelFileWriter and TeNdiPattern are good to go!

TeNdiPattern code is super simple -- it's just 1:1 mapping incoming data to pixels, where the incoming "video" stream is really a vector of ordered pixels.

ModelFileWriter, maybe there are a couple more minor optimizations we could add, but it is fast enough, and works well.  I just tested with TouchDesigner, and it all looks great.

![TDTest1](https://github.com/user-attachments/assets/5c4f72ba-620a-4d09-9078-160fd07ad9a5)

2024-07-13 21:58 UTC, sina-cb commented on .gitignore
> +TD/TE-Projection/Backup/
The TD app generates this. And I just added a new entry here following the gitignore that was already added a while ago. I think a local gitognore would be nice. Moved it.

2024-07-13 22:00 UTC, sina-cb commented on src/main/java/titanicsend/pattern/jon/ModelFileWriter.java
> +      doneWriting = true;
Good point. moved it.

2024-07-13 22:01 UTC, sina-cb commented on src/main/java/titanicsend/pattern/sinas/TdNdiPattern.java
> +  protected NDIEngine ndiEngine;
yeah, I think the formatter wasn't run on this file before. it was okay, but to be consistent I did the formatting on all of the file.

2024-07-13 22:02 UTC, sina-cb commented on Projects/CoachellaMaster.lxp
I must have forgotten to revert it back. I usually test on the default project file and revert before committing. I should ask you all how you set up a project to be default without changing the .lxpreference (or maybe it was another file) file on git

2024-07-19 14:18 UTC, jkbelcher reviewed
My gut here is to gitignore the resources/model folder to reduce noise as these PNGs and CSVs files turn over.  They will be outdated every time a panel or edge moves which is all the time. @zranger1 what do you think?

2024-07-21 23:01 UTC, jkbelcher commented
BTW thanks for relocating the app and trimming this PR down to a much more manageable size.

2024-07-22 00:36 UTC, jkbelcher commented on src/main/java/titanicsend/pattern/jon/ModelFileWriter.java
> +    writeModel(panel_points_list, "panels");
Edit: those collections are working fine.  I had the Mothership model loaded instead of TE.

2024-08-02 02:59 UTC, sina-cb commented
The follow on PR is here:
https://github.com/titanicsend/LXStudio-TE/compare/sinas/te_separate/panels?expand=1

2024-08-09 13:51 UTC, jkbelcher approved these changes

2024-08-09 13:57 UTC, jkbelcher commented
Approving for merge but there are unresolved conversations from that aren't visible because there was a force-push after they happened. Recommend not using force-push once things are under collaboration. I'll let you guys sort that out... @sina-cb @zranger1 can you mark those conversations as resolved?

2024-08-11 12:05 UTC, sina-cb commented
> This works very well! Just for the sake of neatness, remove the unused imports, and I'll approve.
> 
> And thanks for talking to projection people and figuring out what they needed! In my corner of the universe, uv coordinates are always 0.0 to 1.0 floating point. Never would've occurred to me that they'd want something different.

This should be done. I will reach out to Jon to resolve this.

2024-08-11 23:13 UTC, zranger1 approved these changes

2024-08-12 04:34 UTC, jkbelcher commented
Feel free to merge when ready.

2024-08-12 16:49 UTC, merged

2024-08-12 16:49 UTC, sina-cb commented
Yay! Thank you guys! :)