Color Controls: LXComponent, with UI embedded in right performance pane
titanicsend/LXStudio-TE pull request #505
Opened 2024-07-16 01:42 UTC by andrewlook

## TLDR

Similar to the idea of "cue" and "aux", I added two independent sets of color controls, so we can tweak and prepare two color palettes alongside each other.

![image](https://github.com/user-attachments/assets/4ff87852-6afb-4c0b-8583-c9b5b1e5d24d)

## Details

The very top row has a view of Chromatik's global active palette. Below that are two sets of color controls.

Each set of color controls has:
- **Sliders for hue, saturation, and brightness**
- **Knob for "Color Palette Type" selection**, with the following options:
  - `MONOCHROME`, `ANALOGOUS` (+/- 30 on hue wheel), `COMPLEMENTARY` (+180), `TRIADIC` (+/- 120), `SPLIT_COMPLEMENTARY` (+150, +210), and `GOLDEN_RATIO_CONJUGATE` (`hue * 0.618033`, shout-out to @zranger1  for that idea!)
- **Miniature color palette preview**, with a larger rectangle for the color selected via hue/saturation sliders, and two smaller squares for the colors selected by the palette type knob (I wanted to emphasize that the hue/sat sliders are manipulating one color, and the other colors are dependent - open to suggestions on how this could work!)
- **SWAP** button, to push the cue'd up colors live into Chromatik's global active palette.

2024-07-17 00:25 UTC, jkbelcher commented
Hey lots of discussion to be had from this. Overall the direction is great.  Big things I like:

- Forces good color combinations through fixed offsets
- Adds visual preview of the main color & offsets while still being wide open to any main color

2024-07-17 00:29 UTC, jkbelcher commented
An upgrade from displaying the knob, maybe not top priority, would be to display all the Color Palette Types.  Right now you're choosing between a set of things but can only see one of the things at a time.

2024-07-17 00:31 UTC, jkbelcher commented
>  if the palettes get deleted mid-show, should they get re-created instantly?

 Yes.  You'll have to make sure it works around file close/open too.  Don't create them if they're disposing for a file close.  Do create them if a file opened that didn't have them.

2024-07-17 00:35 UTC, jkbelcher commented
The names `CUE` and `AUX` already have a distinct role as cue = main preview (and left side preview in Performance mode), and Aux = right side preview in Performance mode.  May be good to have distinct names to keep people from thinking they're locked together. `ColorA` and `ColorB`?

2024-07-17 00:55 UTC, andrewlook commented
> The names `CUE` and `AUX` already have a distinct role as cue = main preview (and left side preview in Performance mode), and Aux = right side preview in Performance mode. May be good to have distinct names to keep people from thinking they're locked together. `ColorA` and `ColorB`?

very good point, i realized later that cue/aux were already used but I wanted a similar concept of "something that's on deck but the audience can't see". `A` and `B` sound better 👍

2024-07-17 00:56 UTC, andrewlook commented
> > if the palettes get deleted mid-show, should they get re-created instantly?
> 
> Yes. You'll have to make sure it works around file close/open too. Don't create them if they're disposing for a file close. Do create them if a file opened that didn't have them.

This sounds sensible, I'll come up with a set of test cases i can run through manually.

One clarification: "if they're disposing for a file close" - how would I be able to distinguish whether this is happening?

2024-07-17 00:59 UTC, jkbelcher requested changes
Only had a few minutes but here are a couple things to dig on!

2024-07-17 00:59 UTC, jkbelcher commented on src/main/java/titanicsend/ui/effect/UIColorPaletteManager.java
> +          auxMgr.toggleCue,
This can be self-contained in the manager class.  Such as from the constructor:
`this.toggleClue.addListener(...)`

2024-07-17 00:59 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  public void updateSwatches() {
The CUE swatch already has the current colors.  Something like
`this.managedSwatch.recall.trigger()`

...Should move to that swatch while honoring the Color Palette transition controls.

2024-07-17 01:00 UTC, andrewlook commented
> An upgrade from displaying the knob, maybe not top priority, would be to display all the Color Palette Types. Right now you're choosing between a set of things but can only see one of the things at a time.

Ooh yeah great idea! I was thinking it would be cool to somehow do it on the APC mini potentially, so the button grid could display the palettes 🤔

2024-07-19 14:37 UTC, jkbelcher commented
`Is there anything I need to do in terms of saving custom UI state to LXP? I believe the addParameter calls in ColorPaletteManager should save the parameter states, but I'm not sure if I'm missing anything.`
Technically not saving the UI.  You're saving the component underlying the UI.

By extending `LXComponent` and calling `lx.engine.registerComponent(...)`, all the parameters you called `addParameter()` for will be saved/loaded.

2024-07-19 15:14 UTC, jkbelcher requested changes
Hey looking great so far.  Tried to clarify some details so you can keep momentum on it.

2024-07-19 15:14 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  public void onParameterChanged(LXParameter parameter) {
`@Override`

2024-07-19 15:14 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  public void onParameterChanged(LXParameter parameter) {
in the onParameterChanged() method, standard practice is to check the parameter to make sure it's what you're trying to monitor.

```
// Did anything change that would affect output color?
if (parameter == this.hue || parameter == this.saturation || parameter == this.brightness || parameter == this.currPaletteType ) {
  // yep! Update the cue swatch.
}
```

2024-07-19 15:14 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  protected LXPalette lxPalette() {
I think you did this to shorten the characters in all the palette calls.  Opinion here but I think this reduces readability... when I see lxPalette() in code I don't know if it's simple or complicated behind it.  And pulling it into a `protected` method implies a child class might override it.  And that context is beyond what I can infer from code.

2024-07-19 15:47 UTC, jkbelcher requested changes
More comments

2024-07-19 15:47 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  protected void updateSwatches(LXSwatch swatch) {
Nitpick: missing a newline

2024-07-19 15:47 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  public PaletteType currPaletteType = PaletteType.TRIADIC;
No need to monitor the last known value here.  See notes below for using onParameterChanged() to monitor for any changes to the seed parameters, after which you can update the other colors.

2024-07-19 15:47 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +              "Destination color position (1-based) in the global palette current swatch");
Copy/paste description doesn't match

2024-07-19 15:47 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +      new EnumParameter<PaletteType>("Color Position", PaletteType.TRIADIC)
"Palette Type" instead of "Color Position"?

2024-07-19 15:47 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  public LXSwatch managedSwatch;
This should be `private`, don't want another class changing it.

2024-07-19 15:47 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +    LXSwatch cueSwatch = lxPalette().swatches.get(this.index);
I think this is fine for now and we could leave deletion-detection for a later PR.

2024-07-19 15:47 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +    if (this.paletteType.getEnum() == PaletteType.MONO) {
`switch (this.paletteType.getEnum()) {`

2024-07-19 15:47 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +    this.currPaletteType = this.paletteType.getEnum();
Not needed

2024-07-19 15:47 UTC, jkbelcher commented on src/main/java/titanicsend/ui/effect/UIColorPaletteManager.java
This is is package `titanicsend.ui.effect` but seems like `titanicsend.ui.color` would be more appropriate?

2024-07-20 18:30 UTC, andrewlook commented on src/main/java/titanicsend/ui/effect/UIColorPaletteManager.java
ah thanks, that was left over from a refactor - updated now.

2024-07-20 18:35 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +          .setPolarity(CompoundParameter.Polarity.BIPOLAR)
done

2024-07-20 18:35 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +          .setPolarity(CompoundParameter.Polarity.BIPOLAR)
done

2024-07-20 18:37 UTC, andrewlook commented on src/main/java/titanicsend/ui/effect/UIColorPaletteManager.java
sg, done

2024-07-20 18:41 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +    setColorAtPosition(swatch, this.color1Pos.getEnum(), this.color1.getColor());
good call, done

2024-07-20 18:43 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  protected void setColorAtPosition(LXSwatch swatch, DmxColorModulator.ColorPosition colorPosition, int color) {
i just used TEColorType and got the swatch index inside this function 👍

2024-07-20 18:44 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  public void onParameterChanged(LXParameter parameter) {
done

2024-07-20 18:52 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +    if (this.paletteType.getEnum() == PaletteType.MONO) {
done

2024-07-20 18:59 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +    LXSwatch cueSwatch = lxPalette().swatches.get(this.index);
sounds good - i tested this, and when you delete the "cue" palette, the next time you update any of the color controls it takes the top palette and renames it to "cue" (or second palette for "aux").

I noticed though that if you delete all of the swatches, it would crash - so just to be safe I moved a couple lines of code down from the constructor to ensure enough swatches exist.

2024-07-20 19:03 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  public LXSwatch managedSwatch;
done

2024-07-20 19:07 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +      new EnumParameter<PaletteType>("Color Position", PaletteType.TRIADIC)
👍

2024-07-20 19:07 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +              "Destination color position (1-based) in the global palette current swatch");
fixed

2024-07-20 19:08 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  protected LXPalette lxPalette() {
good call, done

2024-07-20 19:32 UTC, andrewlook commented on src/main/java/titanicsend/ui/effect/UIColorPaletteManager.java
> +          auxMgr.toggleCue,
this is super helpful, thank you!

2024-07-20 19:54 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  public void onParameterChanged(LXParameter parameter) {
I replaced these with listeners on the individual params 👍

2024-07-20 19:54 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  public PaletteType currPaletteType = PaletteType.TRIADIC;
👍

2024-07-20 20:00 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  public void updateSwatches() {
made this change. Just FYI, it doesn't actually use the transition time even when transitions are enabled in the global palette pane.

2024-07-21 22:26 UTC, jkbelcher requested changes
Looking much better!  Mainly nitpicky details and style comments now.

2024-07-21 22:26 UTC, jkbelcher commented on src/main/java/titanicsend/ui/color/UIColorPaletteManager.java
> +      // use reflection to access the private field `mainContext` in `LXStudio.UI`
We don't want to be doing this but I'll leave it for now until we can establish a proper method in upstream.

2024-07-21 22:26 UTC, jkbelcher commented on src/main/java/titanicsend/ui/color/UIColorPaletteManager.java
> +        .addToContainer(parentContainer, parentContainer.getChildren().size()-1);
Ideally [later] we could get this above the existing Color Palette in the right performance pane.

2024-07-21 22:26 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  }
Need to initialize color1 in the constructor to the current values of hue/sat/bright.  Otherwise your color1 is black until a component is modified, and if pinned it pushes black to palette.

2024-07-21 22:26 UTC, jkbelcher commented on Projects/TestColorPaletteManager.lxp
This looks like a test file not needed in the repo. ?

2024-07-21 22:26 UTC, jkbelcher commented on src/main/java/heronarts/lx/studio/TEApp.java
> +      lx.engine.registerComponent("paletteManagerA", this.paletteManagerA = new ColorPaletteManager(lx, "SWATCH A", 0));
Simplify to `new ColorPaletteManager(lx)` ?

2024-07-22 00:29 UTC, andrewlook commented on Projects/CoachellaMaster.lxp
no, thanks for catching - reverted them using:

```sh
git checkout main

cp Projects/CoachellaMaster.lxp ~/Desktop

git checkout look/color-controls-device

cp ~/Desktop/CoachellaMaster.lxp Projects
```

2024-07-22 00:30 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> + * Copyright 2013- Mark C. Slee, Heron Arts LLC
removed 👍

2024-07-22 00:31 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  public void dispose() {
ok sounds good. personally i like having the teardown live near the setup, but if it's a style thing that works for me - just changed it

2024-07-22 00:31 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +          .setPolarity(CompoundParameter.Polarity.BIPOLAR)
removed 👍

2024-07-22 00:35 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  public final BooleanParameter pushSwatch =
whoa cool! thanks for the trick 🙌

2024-07-22 00:36 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  private final LXParameterListener pushListener = (p) -> this.pushToActiveSwatch();
gotcha, thanks for explaining!

2024-07-22 00:41 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +    this.managedSwatch = managedSwatch();
ah yes, good catch. fixed.

2024-07-22 00:42 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  private void setColorAtPosition(LXSwatch swatch, TEColorType teColorType, int color) {
done 👍

2024-07-22 00:42 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +    swatch.getColor(teColorType.swatchIndex()).primary.setColor(color);
done 👍

2024-07-22 00:43 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +}
this is good feedback, thanks!

2024-07-22 00:46 UTC, andrewlook commented on Projects/TestColorPaletteManager.lxp
thanks, removed. I also added a line to `.gitignore` for `Projects/Test*.lxp`, since this is probably a relatively common case

2024-07-22 00:51 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  }
i made this change - though when i have an LXP file open, save it, and re-open it, my color1 seems to have been reloaded from disk properly. The only case where I think it'd be unset is when a new LXP file is created, is that right? Just wanted to solidify my understanding of this.

2024-07-22 00:52 UTC, andrewlook commented on src/main/java/heronarts/lx/studio/TEApp.java
> +      lx.engine.registerComponent("paletteManagerA", this.paletteManagerA = new ColorPaletteManager(lx, "SWATCH A", 0));
done

2024-07-22 00:53 UTC, andrewlook commented on src/main/java/titanicsend/ui/color/UIColorPaletteManager.java
> +      // use reflection to access the private field `mainContext` in `LXStudio.UI`
yeah, this is the only way to do what we want to do here. Would really love if this wasn't private upstream, lmk if there's anything I can do to help there!

2024-07-22 00:57 UTC, andrewlook commented on src/main/java/titanicsend/ui/color/UIColorPaletteManager.java
> +        .addToContainer(parentContainer, parentContainer.getChildren().size()-1);
Ideally yes. I had some trouble navigating how LX UI works, particularly when absolute positioning is involved (which it seems to be for the top-level panes). One idea I had was to outright replace the existing performance color palette (since we can fairly easily show a superset of the same information).

As far as I understand, we'd either have to:

(a) have `UIColorPaletteManager` extend `UIPerformancePalette`, so that we could hot-swap it into this list:

```java
    public class MainContext extends UI2dContext {
      public final UILeftPane leftPane;
      public final UIRightPane rightPane;
      public final UIPerformancePane leftPerformance;
      public final UIPerformancePane rightPerformance;
      public final UIPerformanceAudio performanceAudio;
      public final UIPerformancePalette performancePalette; // <-- 
```

or (b) somehow figure out how to fit a new top-left UI pane so that the right panes resize themselves appropriately.

I think option (a) would be fairly easy to try, but yeah I'd rather try it in a separate PR once we have this one merged and can test the basic plumbing.

2024-07-22 01:00 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +        color2 = LXColor.BLACK;
My assumption here was to mirror how our monochromatic palettes have worked in the past, with one color entry and the remaining ones black:

![image](https://github.com/user-attachments/assets/34afc2b9-fa21-4e85-810a-77af9ee40477)

Now that I think about it, if we're doing the per-pattern gradient offset knob, it'd be easier not to check for black and disable gradient offset - so I'll go ahead and change this.

2024-07-22 01:01 UTC, jkbelcher commented on Projects/CoachellaMaster.lxp
I looked up how to do this in one branch:

`git log`
(find commit hash before file was modified)
`git checkout <commit-hash> -- <file-path>`
(now you have the old version of the file)
```
git add <file-path>
git commit -m "Revert <file-path>"
```

2024-07-22 01:05 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +        color2 = LXColor.BLACK;
Yeah I always found those singles annoying in their different behavior.

2024-07-22 01:06 UTC, jkbelcher commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  }
Yes, or at application start the LXP opened was before this component existed.

2024-07-22 01:14 UTC, jkbelcher commented
For a future PR, the PALETTE MANAGER could be shortened.  Also the ui boxes init to black:

<img width="186" alt="image" src="https://github.com/user-attachments/assets/a7a10017-d603-4358-9293-ede07ab7c9cb">

2024-07-22 01:15 UTC, jkbelcher approved these changes
Solid round of work right there!

2024-07-22 01:15 UTC, merged

2024-07-22 02:02 UTC, andrewlook commented on src/main/java/titanicsend/color/ColorPaletteManager.java
> +  }
makes sense, thank you